name: Debug Build

on:
  workflow_dispatch:

jobs:
  debug-windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Show Directory Structure
      run: |
        echo "=== Root Directory ==="
        dir
        echo "=== Source Directory ==="
        dir src\main
        echo "=== Include Directory ==="
        dir include
        
    - name: Create Directories
      run: |
        mkdir data
        mkdir credentials
        mkdir logs
        echo "Directories created"
        
    - name: Configure CMake
      run: |
        echo "Configuring CMake..."
        cmake -B build
        echo "CMake configuration complete"
        
    - name: Build Project
      run: |
        echo "Building project..."
        cmake --build build --config Release --verbose
        echo "Build complete"
        
    - name: Check Build Output
      run: |
        echo "=== Build Directory ==="
        dir build
        echo "=== Release Directory ==="
        dir build\Release
        echo "=== Looking for EXE ==="
        if (Test-Path "build\Release\campus.exe") {
          Write-Host "✅ EXE Found!"
          Get-Item "build\Release\campus.exe"
        } else {
          Write-Host "❌ EXE Not Found"
          Get-ChildItem build -Recurse -Name "*.exe"
        }