name: Minimal Build

on:
  push:
    branches: [ main ]

jobs:
  windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build
      run: |
        cmake -B build
        cmake --build build --config Release
        
    - name: Check Output
      run: |
        echo "Checking build output..."
        dir build\build\Release\ 2>nul || echo "Release dir not found"
        dir build\ 2>nul || echo "Build dir not found"
        
    - name: Find EXE
      run: |
        echo "Looking for campus.exe..."
        where /r build campus.exe 2>nul || echo "campus.exe not found anywhere in build"