name: Minimal Build

on:
  push:
    branches: [ main ]

jobs:
  windows:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - run: |
        echo "Creating directories..."
        if not exist data mkdir data
        if not exist credentials mkdir credentials
        if not exist logs mkdir logs
        
    - run: |
        echo "Configuring CMake..."
        cmake -B build
        
    - run: |
        echo "Building..."
        cmake --build build --config Release
        
    - run: |
        echo "Checking output..."
        dir build\Release
        if exist "build\Release\campus.exe" (
          echo SUCCESS: EXE found
        ) else (
          echo FAILED: EXE not found
          dir build /s
        )
        
    - if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: build/