name: Simple Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  windows-only:
    name: Windows Build Only
    runs-on: windows-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Configure CMake
      run: cmake -B build
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: List Build Output
      run: |
        echo "Build directory contents:"
        dir build\ 2>nul || echo "Build dir not found"
        dir build\Release\ 2>nul || echo "Release dir not found"
        dir build\Debug\ 2>nul || echo "Debug dir not found"
        
    - name: Verify Build
      run: |
        if (Test-Path "build\Release\campus.exe") {
          Write-Host "✅ SUCCESS: campus.exe found in Release"
          Get-Item "build\Release\campus.exe" | Select-Object Name, Length, LastWriteTime
        } elseif (Test-Path "build\campus.exe") {
          Write-Host "✅ SUCCESS: campus.exe found in root"
          Get-Item "build\campus.exe" | Select-Object Name, Length, LastWriteTime
        } else {
          Write-Host "❌ FAILED: campus.exe not found"
          Write-Host "Build directory contents:"
          Get-ChildItem "build" -Recurse -ErrorAction SilentlyContinue | Select-Object Name, FullName
          exit 1
        }
      
    - name: Upload Binary
      uses: actions/upload-artifact@v3
      with:
        name: campus-windows-simple
        path: |
          build/Release/campus.exe
          build/campus.exe
          lib/hpdf.dll