name: Test Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure
      run: cmake -B build
      
    - name: Build
      run: cmake --build build
      
    - name: Find EXE
      run: |
        echo "Looking for campus.exe..."
        if (Test-Path "build\Debug\campus.exe") {
          Write-Host "✅ Found: build\Debug\campus.exe"
          Get-Item "build\Debug\campus.exe"
        } elseif (Test-Path "build\Release\campus.exe") {
          Write-Host "✅ Found: build\Release\campus.exe"
          Get-Item "build\Release\campus.exe"
        } else {
          Write-Host "❌ campus.exe not found"
          Get-ChildItem -Path build -Recurse -Name "*.exe" -ErrorAction SilentlyContinue
        }
        
    - name: Upload
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: build/